const ADMIN_PAGES_PATH = './views/backoffice/pages';
const APP_PORT = 2000;
const APP_STATIC_FOLDER = './public';

const STATUS_CREATED = 'Created Successfully.';
const STATUS_UPDATED = 'Updated Successfully.';
const STATUS_DELETED = 'Deleted Successfully.';
const ALREADY_EXIST  = 'Already Exist.';

const STATUS_CREATED_CODE = 201;
const STATUS_UPDATED_CODE = 123;
const STATUS_DELETED_CODE = 200;
const ALREADY_EXIST_CODE  = 422;

module.exports = {
 ADMIN_PAGES_PATH, APP_PORT, APP_STATIC_FOLDER, STATUS_CREATED, STATUS_UPDATED, STATUS_DELETED, ALREADY_EXIST, STATUS_CREATED_CODE, ALREADY_EXIST_CODE,
 STATUS_DELETED_CODE, STATUS_UPDATED_CODE
}